# Generated by Django 3.0.4 on 2020-03-23 22:11

import PVLV_games.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PVLV_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_bits', models.IntegerField(default=10)),
                ('last_bit_farm', models.DateTimeField(default=django.utils.timezone.now)),
                ('spent', models.IntegerField(default=0)),
                ('given', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('harvest_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_planted', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('planted_value', models.IntegerField(default=0)),
                ('water_used', models.IntegerField(default=1)),
                ('multiplier_value', models.FloatField(default=0.01)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_pass', models.CharField(default='', max_length=100)),
                ('bill', models.OneToOneField(default=PVLV_games.models.Bill.get_new, on_delete=django.db.models.deletion.CASCADE, to='PVLV_games.Bill')),
                ('plant', models.OneToOneField(default=PVLV_games.models.Plant.get_new, on_delete=django.db.models.deletion.CASCADE, to='PVLV_games.Plant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PVLV_users.User')),
            ],
        ),
    ]
