# Generated by Django 3.0.4 on 2020-03-23 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time_zone', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('country', models.IntegerField(default=0)),
                ('vip_code', models.IntegerField(default=0)),
                ('deep_logging', models.BooleanField(default=True)),
                ('suspended', models.BooleanField()),
                ('verification_code', models.IntegerField(default=0)),
                ('game_pass', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_app_id', models.IntegerField()),
                ('app_type', models.CharField(choices=[('T', 'Telegram'), ('D', 'Discord')], max_length=15)),
                ('username', models.CharField(max_length=100)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PVLV_users.User')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
